@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(tester, "Game tester")
System_Verification(c1, "Debugging") {
    Context(web_app, "Web Application", "Dreams", "Use testing methods to detect bugs")
}
System(dreams, "Dreams")

Rel(tester, web_app, "Uses", "HTTPS")
Rel_L(web_app, dreams, "Gets check", "HTTPS")
@enduml
