@startuml
left to right direction
skinparam packageStyle rect
actor teamLeader
actor tester
actor designer
actor programmer
actor soundDirector
rectangle AllTasks {
teamLeader -- (DistributionOfTasks)
(DistributionOfTasks) .> (Supervision) : include
teamLeader -- (ProjectPresentation)
(DistributionOfTasks) -- tester
tester -- (TestingOfEveryAspectOfTheFinalProduct)
(DistributionOfTasks) -- designer
designer -- (CharacterAnimation)
designer -- (design)
(design) .> (EnvironmentalDesign) : include
(design) .> (CharacterDesign) : include
(DistributionOfTasks) -- programmer
programmer -- (programming)
(programming) .> (ProgrammingCharacterBehaviorModel) : include
(programming) .> (WeaponProgramming) : include
(DistributionOfTasks) -- soundDirector
soundDirector -- (SoundProduction)
}
@enduml
